name: build-and-test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -B build -S . -DWEIR_FETCH_DEPENDENCIES=ON -DCMAKE_BUILD_TYPE=Debug -DWEIR_HAPROXY_REPO_URL=https://github.com/haproxy/haproxy.git
    - name: build
      run: cmake --build ./build
    - name: test
      run: ctest --verbose --test-dir ./build

